import * as admin from 'firebase-admin'
admin.initializeApp()

export { adminFunction } from './Admin'
export { addAnalytics } from './Analytics'
export { app } from './App'
export { rateCard, cardCreated, cardUpdated, cardDeleted } from './Card'
export { cardDraftCreated, cardDraftUpdated, cardDraftDeleted } from './CardDraft'
export { sendDueCardNotifications } from './CardNotification'
export { deckCreated, deckUpdated, deckDeleted, viewDeck, rateDeck, addDeck, clearDeckData, deleteDeck } from './Deck'
export { exportDeck } from './Export'
export { historyCreated } from './History'
export { confirmInvite } from './Invite'
export { permissionCreated, permissionUpdated, permissionDeleted } from './Permission'
export { ratingDraftCreated, ratingDraftUpdated, ratingDraftDeleted } from './RatingDraft'
export { settingCreated, settingUpdated, settingDeleted } from './Setting'
export { getUserSignInToken, checkUserSignInToken, getUserDecks, createCardWithSignInToken } from './SignInToken'
export { uploadCreated, uploadUpdated, uploadDeleted, uploadStorageFinalized } from './Upload'
export { userCreated, userUpdated, userDeleted, updateLastOnline, viewUser, followUser, unfollowUser, contactUser, followerCreated, followerUpdated, followerDeleted, followingCreated, followingUpdated, followingDeleted, deckAdded, deckRemoved } from './User'